### ISSUE TITLE
Role & Guard Name Not Displaying

### ISSUE THREAD

**Issue by abbasmashaddy72** [bezhanSalleh/filament-shield#322] opened 2024-01-24 05:15 UTC
Hi,

I am using [Resource Lock Package](https://filamentphp.com/plugins/kenepa-resource-lock)

`composer require kenepa/resource-lock`

After Installing it, I am unable to See the Role & Guard Name

When Edit the Role

Showing this error and When Saving it creates New Role
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null`

I tried to fix it by publishing the files but unable to fix it in both shield Package and Resource Lock Package But Was Unable to achieve it.

You Also Check my [Repo](https://github.com/abbasmashaddy72/filament-starter-kit)

@Jehizkia

**Comment by eelco2k** [comment] 2024-01-24 14:12
have you tried customizing the permissions identifier by adding this code below in AppServiceProvider.php

```
 // customize the Shield Permissions resource identifier in db
        FilamentShield::configurePermissionIdentifierUsing(
            function ($resource) {
                $str = str($resource::getModel())
                    ->prepend('::')->toString();
                return $str;
            }
        );
```

Kenapa resourcelock conflicts with the class path naming convention.. so use another convention for the Resource permissions in your permissions table.

**Comment by abbasmashaddy72** [comment] 2024-01-27 23:17
> have you tried customizing the permissions identifier by adding this code below in AppServiceProvider.php
> 
> 
> 
> ```
> 
>  // customize the Shield Permissions resource identifier in db
> 
>         FilamentShield::configurePermissionIdentifierUsing(
> 
>             function ($resource) {
> 
>                 $str = str($resource::getModel())
> 
>                     ->prepend('::')->toString();
> 
>                 return $str;
> 
>             }
> 
>         );
> 
> ```
> 
> 
> 
> Kenapa resourcelock conflicts with the class path naming convention.. so use another convention for the Resource permissions in your permissions table.
> 
> 
> 
> see: https://github.com/kenepa/resource-lock/issues/13
> 
> 
> 
> 

I will check today

**Comment by bezhanSalleh** [comment] 2024-01-28 10:34
haven't used that package, so if someone can find the cause whether its shield or the package itself. then i would be able to provide a solution. for now i'm closing this issue since its undermined and will reopon once all the facts are in.

**Closed by bezhanSalleh** 2024-01-28 10:34 UTC
