### ISSUE TITLE
Target class [App\Policies\RolePolicy] does not exist.

### ISSUE THREAD

**Issue by DrewNeon** [bezhanSalleh/filament-shield#286] opened 2023-12-13 04:28 UTC
First of all, I'd post this in the "Question" section, but the link is dead, please check: https://github.com/bezhanSalleh/filament-shield/discussions/new?category=q-a

After following the four installation steps as instructed, nothing happened to my admin panel, i.e. there's no menu item leading to Shield. Then I tried the command `php artisan shield:publish`. The resource files were successfully published as shown below:

<img width="248" alt="image" src="https://github.com/bezhanSalleh/filament-shield/assets/25809783/55a58966-549a-4dd5-bf6e-3fcce39a7896">

However, when the admin panel is refreshed, there's an error message saying `Target class [App\Policies\RolePolicy] does not exist.` What did I miss?

Enviroment Info

```
PHP version: 8.2.13
Laravel version: 10.35.0
Filament version: 3.1.18
Shield version: 3.1.1
```

**Comment by iRaziul** [comment] 2023-12-14 07:58
You can run `php artisan make:policy RolePolicy` to create the policy and avoid the error but I don't know any better solution.
I was also facing the issue and created the policy by myself.

**Comment by bezhanSalleh** [comment] 2023-12-15 13:58
> You can run `php artisan make:policy RolePolicy` to create the policy and avoid the error but I don't know any better solution. I was also facing the issue and created the policy by myself.

@iRaziul Not helpful!

@DrewNeon the reason you are facing the issue is, the policy is enabled by default, but it gets generated when you install. so the the check for policy boots up before there is a policy. but clearing your cache and config will get rid of it. this will be fixed in the next release.

**Closed by bezhanSalleh** 2023-12-15 13:58 UTC

**Comment by DrewNeon** [comment] 2023-12-16 09:53
Nice! Waiting for the next release then.
